"""Idempotent starter playbook templates. Original educational frameworks — not guaranteed strategies."""

from __future__ import annotations

import uuid

TEMPLATE_NS = uuid.UUID("7c5cbf00-4a11-4e2a-9c01-playbook00001".replace("playbook00001", "a1b2c3d4e5f6"))


def _id(slug: str) -> uuid.UUID:
    return uuid.uuid5(TEMPLATE_NS, slug)


def _item(label: str) -> dict:
    return {"id": str(uuid.uuid5(TEMPLATE_NS, label)), "label": label}


def _tpl(
    *,
    slug: str,
    title: str,
    icon: str,
    description: str,
    categories: list[str],
    tags: list[str],
    style: str,
    entry: list[str],
    confirmation: list[str],
    risk: list[str],
    exit_rules: list[str],
    notes: str,
    checklist: list[str],
    featured: bool = False,
    order: int = 0,
) -> dict:
    return {
        "id": _id(slug),
        "slug": slug,
        "title": title,
        "icon": icon,
        "description": description,
        "categories": categories,
        "tags": tags,
        "creator_name": "System Templates",
        "version": 1,
        "is_system": True,
        "is_featured": featured,
        "status": "published",
        "sort_order": order,
        "rules": {
            "style": style,
            "entry": entry,
            "confirmation": confirmation,
            "risk": risk,
            "exit": exit_rules,
            "notes": notes,
        },
        "checklist": [_item(label) for label in checklist],
    }


SYSTEM_PLAYBOOK_TEMPLATES: list[dict] = [
    _tpl(
        slug="intraday-liquidity-volatility-model",
        title="Intraday Liquidity & Volatility Model",
        icon="🚀",
        description="Starter framework for trading session liquidity and expanding volatility during the active cash session.",
        categories=["intraday", "swing"],
        tags=["liquidity", "volatility", "session"],
        style="Intraday",
        featured=True,
        order=1,
        entry=[
            "Map prior day high/low and overnight range before the session opens.",
            "Wait for a liquidity sweep of a well-defined session extreme.",
            "Enter only after price reclaims the swept level with expanding range.",
        ],
        confirmation=[
            "Volume or range expansion confirms the reclaim.",
            "Higher-timeframe bias agrees with the trade direction.",
            "No major scheduled news inside the planned hold.",
        ],
        risk=[
            "Invalidation sits beyond the swept extreme.",
            "Risk a fixed fraction of the account; do not widen the stop after entry.",
        ],
        exit_rules=[
            "First target at the opposite session range or next liquidity pool.",
            "Trail remaining size only after a higher-timeframe close in your favor.",
        ],
        notes="This is an example playbook for structuring session trades, not a signal service.",
        checklist=[
            "Session extremes mapped",
            "Liquidity sweep observed",
            "Reclaim confirmed",
            "Risk defined at invalidation",
        ],
    ),
    _tpl(
        slug="buyer-led-directional-auction",
        title="Buyer-Led Directional Auction",
        icon="📈",
        description="Framework for following a one-sided auction once buyers (or sellers) control value.",
        categories=["intraday"],
        tags=["auction", "initiative", "trend"],
        style="Intraday",
        featured=True,
        order=2,
        entry=[
            "Identify an initiative move that accepts away from value.",
            "Wait for a shallow pullback that holds above (or below) the break.",
            "Enter on continuation as the auction resumes in the initiative direction.",
        ],
        confirmation=[
            "Pullback does not return to the prior value area.",
            "Delta or tape (if used) remains aligned with the initiative side.",
        ],
        risk=["Stop belongs on the other side of the pullback structure.", "Skip the trade if the pullback becomes a full mean-reversion."],
        exit_rules=["Scale at the next imbalance or measured move.", "Exit if initiative fails and price is accepted back into value."],
        notes="Use this template to journal whether you actually waited for acceptance, not just the first spike.",
        checklist=["Initiative move identified", "Value left behind", "Pullback held", "Continuation trigger present"],
    ),
    _tpl(
        slug="market-auction-theory",
        title="Market Auction Theory",
        icon="⚖️",
        description="Starter playbook for trading balance versus imbalance using auction-market concepts.",
        categories=["scaling", "intraday"],
        tags=["value", "balance", "imbalance"],
        style="Intraday",
        order=3,
        entry=[
            "Mark the current value area / balance range.",
            "Fade failed breakouts back into balance, or join accepted breakouts.",
            "Do not mix both modes in the same session without a written reason.",
        ],
        confirmation=["Acceptance = multiple closes outside the range.", "Failure = quick rejection and return to value."],
        risk=["For fades, invalidate on acceptance outside the range.", "For breakouts, invalidate on a return to the midpoint of value."],
        exit_rules=["Fade: target value midpoint or opposite side.", "Breakout: target the next higher-timeframe reference."],
        notes="Write down which mode you are in before the order goes in.",
        checklist=["Value area marked", "Mode chosen (fade or continuation)", "Acceptance/failure observed", "Invalidation set"],
    ),
    _tpl(
        slug="support-and-resistance",
        title="Support and Resistance",
        icon="🧱",
        description="Structured reactions around significant support and resistance zones.",
        categories=["swing"],
        tags=["levels", "reaction", "swing"],
        style="Swing trading",
        featured=True,
        order=4,
        entry=[
            "Identify a higher-timeframe level that has multiple touches or a clear origin.",
            "Wait for a reaction at the level rather than a market order into it.",
            "Enter on the confirmation candle or a retest of the reaction.",
        ],
        confirmation=["Wick rejection or engulfing at the zone.", "Lower-timeframe structure shift in the trade direction."],
        risk=["Invalidation is a decisive close through the zone.", "Size from the zone width, not from conviction."],
        exit_rules=["Predefine the next opposing level as the target.", "Partial at 1R if the next level is far."],
        notes="Levels are references, not magnets. Skip crowded, repeatedly broken zones.",
        checklist=["Higher-timeframe level identified", "Context confirmed", "Entry trigger present", "Risk defined"],
    ),
    _tpl(
        slug="smt-divergence-po3",
        title="SMT Divergence + PO3",
        icon="💎",
        description="Example framework combining correlated-market divergence with a three-phase session model.",
        categories=["scalping", "intraday"],
        tags=["smt", "po3", "correlation"],
        style="Scalping",
        order=5,
        entry=[
            "Compare correlated instruments for a divergence at a session extreme.",
            "Wait for the accumulation → manipulation → distribution sequence to complete.",
            "Enter with the distribution leg only after manipulation fails.",
        ],
        confirmation=["Divergence is at a higher-timeframe level, not mid-range.", "Manipulation wick is reclaimed."],
        risk=["Stop beyond the manipulation extreme.", "Stand down if both instruments make a clean new extreme together."],
        exit_rules=["Target the opposing session range or equal highs/lows.", "Flatten before the next session open if still open."],
        notes="Starter template for journaling SMT + PO3 observations. Not a third-party strategy copy.",
        checklist=["Correlated pair compared", "Session phase identified", "Manipulation reclaimed", "Stop beyond extreme"],
    ),
    _tpl(
        slug="absorption-reversal",
        title="Absorption Reversal",
        icon="🛡️",
        description="Reversal framework when aggressive flow is absorbed at a key level.",
        categories=["scalping", "intraday"],
        tags=["absorption", "reversal", "orderflow"],
        style="Scalping",
        order=6,
        entry=[
            "Locate a level where price stalls despite aggressive prints or large wicks.",
            "Enter after absorption and a shift in short-term structure.",
        ],
        confirmation=["Effort (range/volume) does not produce progress.", "A break of the absorbing candle's midpoint holds."],
        risk=["Invalidation is a close beyond the absorbing wick.", "Reduce size in thin, news-driven tape."],
        exit_rules=["Cover at the origin of the absorbed move.", "Trail if a new initiative auction starts."],
        notes="If you cannot see absorption, skip — do not invent it from a single wick.",
        checklist=["Key level present", "Absorption observed", "Structure shift", "Invalidation beyond wick"],
    ),
    _tpl(
        slug="ttrades-fractal-model",
        title="Fractal Model (H1/M5)",
        icon="🔁",
        description="Higher-timeframe bias on H1 with execution on M5. Original starter fractal process.",
        categories=["intraday"],
        tags=["fractal", "h1", "m5"],
        style="Intraday",
        order=7,
        entry=[
            "Define H1 bias from the most recent impulsive leg and discount/premium.",
            "Drop to M5 only for an entry that agrees with that bias.",
            "Ignore M5 signals that fight the H1 direction.",
        ],
        confirmation=["M5 structure break aligns with H1.", "Entry occurs in discount (longs) or premium (shorts)."],
        risk=["H1 invalidation is the trade invalidation — not the M5 noise.", "One attempt per H1 impulse."],
        exit_rules=["Target the H1 opposing imbalance or swing.", "Exit if H1 closes against the bias."],
        notes="Named as a fractal process template. No affiliation implied.",
        checklist=["H1 bias written", "M5 trigger agrees", "Entry in discount/premium", "H1 invalidation set"],
    ),
    _tpl(
        slug="low-volume-node",
        title="Low Volume Node",
        icon="📉",
        description="Trade acceptance or rejection around low-volume nodes on a volume profile.",
        categories=["scalping", "intraday"],
        tags=["volume-profile", "lvn", "acceptance"],
        style="Scalping",
        order=8,
        entry=[
            "Mark LVNs that sit between high-volume nodes.",
            "Join a move once price is accepted through the LVN, or fade a failed traverse.",
        ],
        confirmation=["Acceptance = hold beyond the node.", "Failure = immediate return to the originating HVN."],
        risk=["Do not fade a strong trend through successive LVNs.", "Stops belong on the far side of the nearest HVN."],
        exit_rules=["Target the next high-volume node.", "Scratch if price stalls inside the LVN."],
        notes="Requires a volume profile. Skip if you only have candlesticks and no node map.",
        checklist=["Profile built", "LVN identified", "Accept or fade decided", "HVN target marked"],
    ),
    _tpl(
        slug="two-touchpoint-break",
        title="2 Touchpoint Break",
        icon="2️⃣",
        description="Break of a two-touch trendline or level after the second confirmation touch.",
        categories=["swing"],
        tags=["trendline", "break", "swing"],
        style="Swing trading",
        order=9,
        entry=[
            "Connect two clean swing points of the same type.",
            "Trade the break only after a close beyond the line and a retest that fails.",
        ],
        confirmation=["Second touch is not a deep overshoot.", "Break close is not an isolated wick."],
        risk=["Invalidation is a close back through the broken line.", "Avoid lines drawn through messy overlapping structure."],
        exit_rules=["Measured move equal to the prior swing, or next HTF level."],
        notes="Two touches define the line. A third touch is a different playbook.",
        checklist=["Two clean touches", "Line not forced", "Close beyond line", "Failed retest"],
    ),
    _tpl(
        slug="three-touchpoint-break",
        title="3 Touchpoint Break",
        icon="3️⃣",
        description="Wait for a third touch of a well-respected line, then trade the break.",
        categories=["swing"],
        tags=["trendline", "third-touch", "swing"],
        style="Swing trading",
        order=10,
        entry=[
            "Require three distinct touches before treating the line as established.",
            "Enter on the break of the third-touch structure, not the third touch itself.",
        ],
        confirmation=["Touches are spaced in time — not the same swing.", "The third touch shows exhaustion (smaller follow-through)."],
        risk=["If the third touch holds and expands, there is no trade.", "Stop beyond the third-touch extreme."],
        exit_rules=["Target the origin of the trendline move.", "Trail after 1.5R."],
        notes="Patience is the rule. Skipping the third touch is a process break.",
        checklist=["Three distinct touches", "Exhaustion on third touch", "Break confirmed", "Stop beyond extreme"],
    ),
    _tpl(
        slug="trendline-bounce",
        title="Trendline Bounce",
        icon="↗️",
        description="Continuation entries off a rising or falling trendline in an established trend.",
        categories=["swing"],
        tags=["trendline", "bounce", "continuation"],
        style="Swing trading",
        order=11,
        entry=[
            "Trade only with the higher-timeframe trend.",
            "Wait for price to return to the trendline and show a bounce trigger.",
        ],
        confirmation=["Trendline has at least two prior respected touches.", "Bounce candle closes back in the trend direction."],
        risk=["Invalidation is a close through the trendline.", "Do not average into a break."],
        exit_rules=["Prior swing high/low, or trail under/above successive higher lows."],
        notes="Bounces fail. Plan the break scenario before you click buy/sell.",
        checklist=["HTF trend agreed", "Trendline respected twice", "Bounce trigger", "Break scenario planned"],
    ),
    _tpl(
        slug="unique-high-rr",
        title="Unique High RR",
        icon="🎯",
        description="Selective setups where invalidation is tight and the next target is structurally far.",
        categories=["swing"],
        tags=["rr", "asymmetric", "selective"],
        style="Swing trading",
        order=12,
        entry=[
            "Only take locations where stop distance is small relative to the next HTF target.",
            "Skip average locations even if they 'look fine'.",
        ],
        confirmation=["Minimum planned R multiple is written before entry.", "Structure allows a clean invalidation, not a wide guess."],
        risk=["If the stop must be wide to 'make it work', pass.", "Cap risk per trade; never enlarge size to force R."],
        exit_rules=["Hold for the written target unless structure is clearly invalidated.", "Partials only if they were in the plan."],
        notes="High R is a location filter, not a reason to oversize.",
        checklist=["Asymmetry written", "Tight invalidation", "HTF target marked", "Size from risk not from R"],
    ),
    _tpl(
        slug="break-and-retest",
        title="Break & Retest",
        icon="↪️",
        description="Classic break of structure with a retest that holds as new support or resistance.",
        categories=["swing"],
        tags=["break", "retest", "structure"],
        style="Swing trading",
        featured=True,
        order=13,
        entry=[
            "Wait for a decisive close through a well-defined level.",
            "Enter on the retest that holds, not on the first break candle.",
        ],
        confirmation=["Break is a close, not a wick.", "Retest fails to close back through the level."],
        risk=["Invalidation is a close back through the broken level.", "Skip if the retest never comes and you are chasing."],
        exit_rules=["Next structure level, or measured move of the break swing."],
        notes="No retest, no trade — unless you have a separate continuation playbook.",
        checklist=["Level defined", "Close through level", "Retest holds", "Stop back through level"],
    ),
    _tpl(
        slug="break-and-retest-intraday",
        title="Break & Retest — Intraday",
        icon="⚡",
        description="Same break-and-retest process compressed to session levels and opening range.",
        categories=["intraday"],
        tags=["break", "retest", "opening-range"],
        style="Intraday",
        order=14,
        entry=[
            "Use opening range, prior day high/low, or session VWAP bands as the level.",
            "Trade the first valid retest after a session break, not every later probe.",
        ],
        confirmation=["Break occurs with range expansion.", "Retest occurs while the session still has time remaining."],
        risk=["Do not hold a failed retest into the next session.", "News windows are automatic stand-downs."],
        exit_rules=["Opposing session extreme or VWAP.", "Flatten into the last hour if still open."],
        notes="Intraday version of break and retest. Faster invalidation, same process.",
        checklist=["Session level marked", "Expansion break", "First retest only", "Flatten before next session"],
    ),
    _tpl(
        slug="amd-playbook",
        title="AMD Playbook",
        icon="🧭",
        description="Accumulation, manipulation, distribution as a session journaling framework.",
        categories=["intraday"],
        tags=["amd", "session", "manipulation"],
        style="Intraday",
        order=15,
        entry=[
            "Label the session's accumulation range first.",
            "Wait for a manipulation swing that takes obvious liquidity.",
            "Enter with the distribution move after the manipulation fails.",
        ],
        confirmation=["Manipulation is at a known liquidity pool.", "Distribution starts with a reclaim of the accumulation edge."],
        risk=["Stop beyond the manipulation extreme.", "If accumulation never forms, there is no AMD trade."],
        exit_rules=["Target the opposing side of the day's range.", "Do not reverse the distribution without a new AMD cycle."],
        notes="Use AMD as a labeling tool in the journal. Force-fitting every morning into AMD is a process error.",
        checklist=["Accumulation labeled", "Manipulation swing", "Reclaim / distribution", "Stop beyond manipulation"],
    ),
]
