"""Canonical trade columns and the header labels that map onto them."""

from __future__ import annotations

# Earlier fields win when one column could fill two of them.
FIELD_ORDER: tuple[str, ...] = (
    "symbol",
    "side",
    "quantity",
    "price",
    "exit_price",
    "executed_at",
    "closed_at",
    "commission",
    "swap",
    "funding",
    "external_id",
    "pnl",
    "gross_pnl",
    "stop_loss",
    "profit_target",
    "risk_amount",
    "leverage",
    "strike_price",
    "notes",
    "emotions",
    "mood",
    "strategy",
    "setup",
    "rules_broken",
    "session",
    "trade_type",
    "rating",
    "entry_condition",
    "exit_condition",
    "asset_type",
    "expiry_date",
    "analysis_timeframe",
    "entry_timeframe",
    "option_type",
)

ALIASES: dict[str, tuple[str, ...]] = {
    "symbol": (
        "symbol",
        "ticker",
        "instrument",
        "product_symbol",
        "item",
        "scrip",
        "stock",
        "pair",
        "market",
        "contract",
    ),
    "side": ("side", "direction", "buy_sell", "action", "transaction_type", "trade_type", "type"),
    "quantity": ("quantity", "qty", "volume", "size", "lots", "shares", "filled_qty", "lot"),
    "price": ("entry_price", "open_price", "price_open", "fill_price", "avg_price", "buy_price", "price", "entry"),
    "exit_price": ("exit_price", "close_price", "price_close", "sell_price", "exit"),
    "executed_at": (
        "executed_at",
        "entry_date_time",
        "open_time",
        "entry_time",
        "opened_at",
        "trade_date",
        "entry_date",
        "date_open",
        "date",
        "time",
        "open_date",
    ),
    "closed_at": (
        "closed_at",
        "exit_date_time",
        "close_time",
        "exit_time",
        "date_close",
        "exit_date",
        "close_date",
    ),
    "commission": ("commission", "fees", "fee", "brokerage"),
    "swap": ("swap", "rollover"),
    "funding": ("funding", "funding_fee"),
    "external_id": (
        "external_id",
        "external_trade_id",
        "ticket",
        "order_id",
        "deal_id",
        "position_id",
        "deal",
        "trade_id",
        "reference",
    ),
    "pnl": ("pnl", "net_pnl", "profit", "p_and_l", "p_l", "pl", "profit_loss", "net_profit"),
    "gross_pnl": ("gross_pnl", "gross_profit", "gross_pl", "gross_p_l"),
    "stop_loss": ("stop_loss", "stoploss", "stop", "sl"),
    "profit_target": ("profit_target", "take_profit", "takeprofit", "tp", "target"),
    "risk_amount": ("risk_amount", "trade_risk"),
    "leverage": ("leverage", "lev"),
    "strike_price": ("strike_price", "strike"),
    "notes": ("notes", "note", "comment", "comments", "journal", "remark", "remarks", "description", "commentary"),
    "emotions": (
        "emotions",
        "emotion",
        "emotion_tags",
        "emotion_tag",
        "feelings",
        "feeling",
        "mindset",
        "sentiment",
    ),
    "mood": ("mood", "mood_score"),
    "strategy": ("strategy", "strategy_name", "playbook", "system"),
    "setup": ("setup", "setups", "setup_tag", "setup_tags"),
    "rules_broken": ("rules_broken", "mistakes", "mistake", "rules", "broken_rules"),
    "session": ("session", "trading_session", "market_session"),
    "trade_type": ("trade_type", "style", "order_style"),
    "rating": ("rating", "trade_rating", "score"),
    "entry_condition": ("entry_condition", "entry_reason"),
    "exit_condition": ("exit_condition", "exit_reason"),
    "asset_type": ("asset_type", "asset_class", "class", "instrument_type"),
    "expiry_date": ("expiry_date", "expiry", "expiration"),
    "analysis_timeframe": ("analysis_timeframe", "timeframe", "tf"),
    "entry_timeframe": ("entry_timeframe",),
    "option_type": ("option_type", "call_put"),
}

REQUIRED_FIELDS: tuple[str, ...] = ("symbol", "side", "quantity", "price", "executed_at")

FIELD_LABELS: dict[str, str] = {
    "symbol": "Symbol",
    "side": "Side",
    "quantity": "Quantity",
    "price": "Entry price",
    "exit_price": "Exit price",
    "executed_at": "Open time",
    "closed_at": "Close time",
    "commission": "Commission",
    "swap": "Swap",
    "funding": "Funding",
    "external_id": "Ticket",
    "pnl": "P&L",
    "gross_pnl": "Gross P&L",
    "stop_loss": "Stop loss",
    "profit_target": "Take profit",
    "risk_amount": "Risk",
    "leverage": "Leverage",
    "strike_price": "Strike",
    "notes": "Notes",
    "emotions": "Emotions",
    "mood": "Mood",
    "strategy": "Strategy",
    "setup": "Setup",
    "rules_broken": "Rules broken",
    "session": "Session",
    "trade_type": "Trade type",
    "rating": "Rating",
    "entry_condition": "Entry condition",
    "exit_condition": "Exit condition",
    "asset_type": "Asset type",
    "expiry_date": "Expiry",
    "analysis_timeframe": "Timeframe",
    "entry_timeframe": "Entry timeframe",
    "option_type": "Option type",
}

# How cell text is read when the header itself is not a known alias.
FIELD_KIND: dict[str, str] = {
    "symbol": "symbol",
    "side": "side",
    "quantity": "number",
    "price": "number",
    "exit_price": "number",
    "executed_at": "datetime",
    "closed_at": "datetime",
    "commission": "number",
    "swap": "number",
    "funding": "number",
    "external_id": "id",
    "pnl": "signed",
    "gross_pnl": "signed",
    "stop_loss": "number",
    "profit_target": "number",
    "risk_amount": "number",
    "leverage": "number",
    "strike_price": "number",
    "notes": "prose",
    "emotions": "emotion",
    "mood": "emotion",
    "strategy": "strategy",
    "setup": "text",
    "rules_broken": "mistake",
    "session": "session",
    "trade_type": "text",
    "rating": "rating",
    "entry_condition": "prose",
    "exit_condition": "prose",
    "asset_type": "asset",
    "expiry_date": "datetime",
    "analysis_timeframe": "timeframe",
    "entry_timeframe": "timeframe",
    "option_type": "option",
}
