/** Primary broker catalog used in onboarding + imports. */

export const BROKER_OPTIONS = [
  "Alpaca",
  "Alpha Futures - Alpha Ticks",
  "AMP Futures - ATAS",
  "AMP Futures - CQG Desktop",
  "AMP Futures - MetaTrader 5",
  "AMP Futures - MotiveWave",
  "AMP Futures - Quantower",
  "AMP Futures - Rithmic R Trader",
  "AMP Futures - Sierra Chart",
  "AMP Futures - TickBlaze",
  "AMP Futures - TradingView Paper Trading",
  "ATAS",
  "ByBit",
  "ByBit - MetaTrader 5",
  "Capital.com",
  "Charles Schwab",
  "Coinbase",
  "CQG Desktop",
  "cTrader",
  "cTrader - Axiory Global",
  "cTrader - BlackBull Markets",
  "cTrader - Deriv",
  "cTrader - Dominion Markets",
  "cTrader - FP Markets",
  "cTrader - FundingPips",
  "cTrader - FxPro",
  "cTrader - Pepperstone",
  "cTrader - PipFarm",
  "cTrader - TopFX",
  "cTrader - TradeView Markets",
  "DasTrader",
  "DxTrade - Alchemy Markets",
  "DxTrade - Alpha Capital Group",
  "DxTrade - Aqua Funded",
  "DxTrade - Blue Guardian",
  "DxTrade - Blueberry Markets",
  "DxTrade - BrightFunded",
  "DxTrade - Demo DXtrade Crypto",
  "DxTrade - Demo DXtrade Forex",
  "DxTrade - Demo DXtrade Stocks & Options",
  "DxTrade - Eightcap",
  "DxTrade - Funded Peaks",
  "DxTrade - Funded Trading Plus",
  "DxTrade - Other servers",
  "DxTrade - Rocket 21",
  "DxTrade - Skilled Funded Trader",
  "DxTrade - Smart Prop Trader",
  "DxTrade - The Funded Trader",
  "DxTrade - Union Wealths Management",
  "DxTrade - VanquishTrader",
  "E-Trade (Power E-Trade)",
  "eToro",
  "FTMO",
  "FTMO - cTrader",
  "FTMO - MetaTrader 4",
  "FTMO - MetaTrader 5",
  "IC Markets - cTrader",
  "IC Markets - MetaTrader 4",
  "IC Markets - MetaTrader 5",
  "Interactive Brokers",
  "Ironbeam",
  "Lightspeed",
  "LSEG",
  "Match-Trader",
  "MetaTrader 4",
  "MetaTrader 5 - AXSE Brokerage Ltd.",
  "MetaTrader 5 - Capital Index (Global) Limited",
  "MetaTrader 5 - Eightcap Ltd.",
  "MetaTrader 5 - Eightcap Pty Ltd",
  "MetaTrader 5 - Exfor Limited",
  "MetaTrader 5 - Exness Technologies Ltd",
  "MetaTrader 5 - Foreign Exchange Clearing House Ltd",
  "MetaTrader 5 - FTMO S.R.O.",
  "MetaTrader 5 - FundedNext Ltd",
  "MetaTrader 5 - Fyntura Limited",
  "MetaTrader 5 - L.F. Investment Limited",
  "MetaTrader 5 - LQD Ltd.",
  "MetaTrader 5 - MetaQuotes Software Corp.",
  "MetaTrader 5 - OANDA Corporation",
  "MetaTrader 5 - Other servers",
  "MetaTrader 5 - Ox Securities Pty Ltd",
  "MetaTrader 5 - Prime Intermarket Group Eurasia LLC",
  "MetaTrader 5 - Raw Trading Ltd",
  "MetaTrader 5 - TF Global Markets (Aust) Pty Ltd",
  "MetaTrader 5 - Tradeslide Trading Tech Limited",
  "MetaTrader 5 - Zenfinex Global Limited",
  "Moomoo",
  "MotiveWave",
  "NinjaTrader",
  "Oanda",
  "ProjectX",
  "ProjectX - Aqua Futures",
  "ProjectX - Blue Guardian Futures",
  "ProjectX - Blusky",
  "ProjectX - Bulenox",
  "ProjectX - DayTraders",
  "ProjectX - E8 Futures",
  "ProjectX - Funding Futures",
  "ProjectX - FuturesElite",
  "ProjectX - FXIFY",
  "ProjectX - Goat Futures",
  "ProjectX - Nexgen Futures",
  "ProjectX - The Futures Desk",
  "ProjectX - TickTickTrader",
  "ProjectX - Top One Futures",
  "ProjectX - TradeDay",
  "ProjectX - TX3 Funding",
  "Quantower",
  "Questrade",
  "Rithmic R Trader",
  "Robinhood",
  "Sierra Chart",
  "Silexx",
  "Sterling Trader Pro",
  "Tastytrade",
  "TC2000",
  "TD Direct Investments",
  "TEFS Evolution",
  "Thinkorswim",
  "TickBlaze",
  "TopstepX",
  "TradeStation",
  "TradeLocker",
  "TradeLocker - 24k Markets",
  "TradeLocker - Aiko Markets",
  "TradeLocker - Athens Markets",
  "TradeLocker - Blu Markets",
  "TradeLocker - DominionEx",
  "TradeLocker - EmpowerFX",
  "TradeLocker - FXSWay",
  "TradeLocker - Genesis Assets",
  "TradeLocker - HeroFX",
  "TradeLocker - Hey Forex",
  "TradeLocker - KOT4X",
  "TradeLocker - LivvFX",
  "TradeLocker - Nash Markets",
  "TradeLocker - NextTrade",
  "TradeLocker - NTW Markets",
  "TradeLocker - OspreyFX",
  "TradeLocker - Plexytrade",
  "TradeLocker - Prolific Markets",
  "TradeLocker - SageFX",
  "TradeLocker - Trident Markets",
  "TradeLocker - Vital Markets",
  "TradeZero",
  "Tradier",
  "TradingView Paper Trading",
  "Tradovate",
  "Webull",
  "Zerodha",
  "Other",
] as const;

export type BrokerOption = (typeof BROKER_OPTIONS)[number];

/** Brand family / exact name → website domain for favicon lookup. */
const BROKER_DOMAINS: Record<string, string> = {
  Alpaca: "alpaca.markets",
  "Alpha Futures": "alphaticks.io",
  "AMP Futures": "ampfutures.com",
  ATAS: "atas.net",
  ByBit: "bybit.com",
  "Capital.com": "capital.com",
  "Charles Schwab": "schwab.com",
  Coinbase: "coinbase.com",
  "CQG Desktop": "cqg.com",
  cTrader: "ctrader.com",
  DasTrader: "dastrader.com",
  DxTrade: "dx.trade",
  "E-Trade (Power E-Trade)": "etrade.com",
  eToro: "etoro.com",
  FTMO: "ftmo.com",
  "IC Markets": "icmarkets.com",
  "Interactive Brokers": "interactivebrokers.com",
  Ironbeam: "ironbeam.com",
  Lightspeed: "lightspeed.com",
  LSEG: "lseg.com",
  "Match-Trader": "match-trader.com",
  "MetaTrader 4": "metatrader4.com",
  "MetaTrader 5": "metatrader5.com",
  Moomoo: "moomoo.com",
  MotiveWave: "motivewave.com",
  NinjaTrader: "ninjatrader.com",
  Oanda: "oanda.com",
  ProjectX: "projectx.com",
  Quantower: "quantower.com",
  Questrade: "questrade.com",
  "Rithmic R Trader": "rithmic.com",
  Robinhood: "robinhood.com",
  "Sierra Chart": "sierrachart.com",
  Silexx: "silexx.com",
  "Sterling Trader Pro": "sterlingtrader.com",
  Tastytrade: "tastytrade.com",
  TC2000: "tc2000.com",
  "TD Direct Investments": "td.com",
  "TEFS Evolution": "tefs.com",
  Thinkorswim: "thinkorswim.com",
  TickBlaze: "tickblaze.com",
  TopstepX: "topstep.com",
  TradeStation: "tradestation.com",
  TradeLocker: "tradelocker.com",
  TradeZero: "tradezero.co",
  Tradier: "tradier.com",
  "TradingView Paper Trading": "tradingview.com",
  Tradovate: "tradovate.com",
  Webull: "webull.com",
  Zerodha: "zerodha.com",
};

function brokerFamily(name: string): string {
  const cut = name.indexOf(" - ");
  return cut === -1 ? name : name.slice(0, cut);
}

export function brokerDomain(name: string): string | null {
  if (name === "Other") return null;
  return BROKER_DOMAINS[name] ?? BROKER_DOMAINS[brokerFamily(name)] ?? null;
}

/** Google favicon CDN — works with plain <img>, no next/image remote config needed. */
export function brokerIconUrl(name: string): string | null {
  const domain = brokerDomain(name);
  if (!domain) return null;
  return `https://www.google.com/s2/favicons?domain=${encodeURIComponent(domain)}&sz=64`;
}

export function brokerInitials(name: string): string {
  const family = brokerFamily(name);
  const parts = family.replace(/[()]/g, "").split(/\s+/).filter(Boolean);
  if (parts.length === 0) return "?";
  if (parts.length === 1) return parts[0].slice(0, 2).toUpperCase();
  return (parts[0][0] + parts[1][0]).toUpperCase();
}

const PALETTE = [
  "bg-primary/15 text-primary",
  "bg-sky-500/15 text-sky-600",
  "bg-violet-500/15 text-violet-600",
  "bg-amber-500/15 text-amber-600",
  "bg-rose-500/15 text-rose-600",
  "bg-indigo-500/15 text-indigo-600",
  "bg-orange-500/15 text-orange-600",
  "bg-pink-500/15 text-pink-600",
];

export function brokerAccentClass(name: string): string {
  let hash = 0;
  for (let i = 0; i < name.length; i++) hash = (hash * 31 + name.charCodeAt(i)) >>> 0;
  return PALETTE[hash % PALETTE.length];
}

export function isKnownBroker(name: string): boolean {
  return (BROKER_OPTIONS as readonly string[]).includes(name);
}
